### ISSUE TITLE
Migration from JCenter

### ISSUE THREAD

**Issue by jakoss** [Chimerapps/niddler#22]
In may this library won't be available from JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please migrate this library to some other repository

**Comment by NicolaChimerapps** [comment]
Oh that's just brilliant, thanks jfrog. Will look into it when I find the time, we will have to move a large number of repos

**Comment by NicolaChimerapps** [comment]
1.4.0 will be published to maven central in time for the shutdown. **HOWEVER** This version will no longer be found under `com.icapps.niddler...` but under `com.chimerapps.niddler...`. This is an intermediate temporary to reduce friction for upgrading.

As part of the migration to maven central, the coordinates and the package have changed.
Starting from 1.5.0 (which is the recommended version live on maven central)
`com.icapps.*` has been replaced by `com.chimerapps.*` in both package names and maven group id

**Comment by NicolaChimerapps** [comment]
I am sorry for the extra work that will be required to handle the migration.

**Comment by jakoss** [comment]
Absolutely not a problem to me, thanks for handling that so fast :)
