### ISSUE TITLE
Issue with 1.6.0 on maven central

### ISSUE THREAD

**Issue by jakoss** [Chimerapps/niddler#28]
When trying to upgrade to 1.6.0 i have this error `Failed to resolve: com.chimerapps.niddler:niddler-base:1.6.0`. And in fact - artifact does not exist there

**Comment by NicolaVerbeeck** [comment]
After again struggling with maven release, this should be rectified. Url-connection is also releasing since I forgot that

**Comment by jakoss** [comment]
Works perfectly, thanks!
